name: postnow
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.2
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.3
  firebase_messaging: ^7.0.3
  firebase_core_web: ^0.2.1
  firebase_database: ^4.3.0
  firebase_storage: ^5.0.1
  firebase_remote_config: ^0.4.2
  cloud_firestore: ^0.14.3

  cupertino_icons: ^0.1.3
  google_maps_webservice: ^0.0.17
  google_maps_flutter: ^0.5.28+1
  google_map_polyline: ^0.2.0+1
  permission_handler: ^5.0.1+1
  geolocator: ^5.3.2+2
  map_launcher: ^0.8.2
  camera: ^0.5.8+2
  image_picker: ^0.6.7+4
  path_provider: ^1.6.11
  path: ^1.6.4
  pinput: ^0.2.4
  easy_localization: ^2.3.3
  flutter_signature_pad: ^2.0.2
  characters: ^1.0.0
  flutter_svg: ^0.18.1
  oktoast: ^2.3.2
  screen: ^0.0.5
  rxdart: ^0.24.1
  package_info: ^0.4.3
  store_redirect: ^1.0.2
  flutter_html: ^1.0.2
  charts_flutter: ^0.9.0
  flutter_speed_dial: ^1.2.5
  url_launcher: ^5.6.0
  swipebuttonflutter: ^0.1.2
  progress_state_button: ^1.0.1
  circular_check_box: ^1.0.4
  audioplayers: ^0.16.1
  vibration: ^1.7.1
  flutter_cupertino_settings: ^0.3.1
  flutter_inappwebview: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  assets:
    - assets/
    - assets/map_styles/
    - assets/translations/
    - assets/sounds/warn.mp3
    - assets/sounds/positive.mp3
    - assets/sounds/negative.mp3
    - assets/sounds/new_order.mp3
    - assets/sounds/push_notification.mp3